"""Endogenous confidence maps.

Confidence is generated by the *same* within-trial decision process that
produces the action (doctrinal commitment iii).  It is a subjective
reliability weight, **not** objective accuracy, and is bounded in (0, 1).

Two maps are provided:

* :func:`confidence_decision` -- the baseline map of Eq. (confidence) in the
  manuscript: increasing in evidence strength ``|v|/a`` and decreasing in
  decision time ``tau``.

* :func:`confidence_balance` -- the *alternative* map used in the ablation
  (replace the time-sensitive map by a balance-of-evidence read-out taken
  directly from the DDM choice probability).  This isolates whether the
  decision-time dependence of confidence matters for the social mechanism.
"""
from __future__ import annotations

import numpy as np
from scipy.special import expit

_EPS = 1e-9


def confidence_decision(v_abs, tau, a, kappa1, kappa2, tau0):
    """Baseline confidence map.

    C = sigmoid( kappa1 * |v| / a  -  kappa2 * log(1 + tau / tau0) ).
    Rises with drift magnitude (evidence strength), falls with decision time.
    """
    v_abs = np.asarray(v_abs, dtype=float)
    tau = np.asarray(tau, dtype=float)
    z = kappa1 * (v_abs / a) - kappa2 * np.log1p(tau / tau0)
    # expit saturates to exactly 0/1 in float64 for large |z|; clip to keep
    # confidence strictly inside (0, 1) as the doctrine requires.
    return np.clip(expit(z), _EPS, 1.0 - _EPS)


def confidence_balance(p_chosen):
    """Alternative confidence map: balance of evidence for the chosen arm.

    ``p_chosen`` is the DDM probability of the chosen boundary, in [0.5, 1).
    Returned confidence is clipped to the open interval (0, 1).
    """
    p_chosen = np.asarray(p_chosen, dtype=float)
    return np.clip(p_chosen, _EPS, 1.0 - _EPS)
