"""Emit every LaTeX table from saved JSON/configs (fully reproducible).

Tables produced (in paper/tables/):
  results_table.tex        Table 1 (baseline + uncertainty) and Table 2
                           (ablation uncertainty + paired counterfactual effects)
  table_scenarios.tex      Table C1 -- scenario parameters per figure
  table_default_params.tex Table C2 -- global default parameters
  table_code_map.tex       Table A1 -- equation / code / test map
  table_robustness.tex     Table D1 -- robustness summary (R1-R7)
"""
import json
import os
import numpy as np
import common
from credibility import scenarios, uncertainty as unc
from credibility.config import Params, SCALE

TABDIR = os.path.abspath(os.path.join(common.FIGDIR, "..", "tables"))
os.makedirs(TABDIR, exist_ok=True)


def _ci(lo, hi):
    return f"[{lo:.2f}, {hi:.2f}]"


def write_results_table(scale):
    base = json.load(open(f"{common.RESULTS}/baseline_{scale}.json"))
    abl = json.load(open(f"{common.RESULTS}/ablations_{scale}.json"))
    av, con = abl["variants"], abl["contrasts_vs_full"]
    L = ["% Auto-generated by scripts/make_tables.py -- do not edit."]
    # ---- Table 1: baseline regimes with uncertainty ----
    L += [r"\begin{table}[t]\centering\small",
          r"\caption{Baseline regimes. Each scenario is run for $R$ Monte Carlo "
          r"replications; the realised regime probability is $1.00$ in every case, "
          r"reported with its Wilson 95\% lower bound. $\mathcal{R}_T$ is mean group "
          r"regret with Monte Carlo standard error. Scenario parameters are in "
          r"Table~\ref{tab:scenarios}.}",
          r"\label{tab:baseline}",
          r"\begin{tabular}{lcccc}\toprule",
          r"Regime & $R$ & $\lambda$ & P(regime) [Wilson 95\% LB] & $\mathcal{R}_T$ (SE) \\ \midrule"]
    for name in ["efficient", "wrong", "polarised"]:
        b = base[name]; R = int(b["R"]); p = b["params"]
        lo, hi = unc.wilson_interval(R, R)
        L.append(f"{name} & {R} & {p['lam']:.2f} & $1.00$ [{lo:.3f}] & "
                 f"{b['mean_regret']:,.0f} ({b['regret_se']:.0f}) \\\\")
    L += [r"\bottomrule\end{tabular}", r"\end{table}"]
    # ---- Table 2: ablations with uncertainty + paired contrasts ----
    pretty = {"full": "full", "no-anticipatory": "no anticipatory",
              "no-retrospective": "no retrospective", "no-confidence-wt": "no credibility wt.",
              "constant-lr": "constant LR", "alt-confidence": "alt.\\ confidence"}
    R = int(abl["R"])
    L += [r"\begin{table}[t]\centering\small",
          r"\caption{Mechanism isolation at the contested operating point "
          r"(Table~\ref{tab:scenarios}), $R=" + str(R) + r"$ replications under common "
          r"random numbers. P(wrong) and P(efficient) carry Wilson 95\% intervals; "
          r"regret carries a 95\% bootstrap interval. The last column is the paired "
          r"counterfactual effect on wrong consensus, "
          r"$\Delta=$P(wrong$\mid$full)$-$P(wrong$\mid$ablation), with a paired "
          r"bootstrap 95\% interval. A positive $\Delta$ whose interval excludes $0$ "
          r"means the component is necessary for the distortion.}",
          r"\label{tab:ablation}",
          r"\begin{tabular}{lcccc}\toprule",
          r"Variant & P(wrong) [95\%] & P(eff.) [95\%] & $\mathcal{R}_T$ [95\%] "
          r"& $\Delta$P(wrong) [95\%] \\ \midrule"]
    for name in ["full", "no-anticipatory", "no-retrospective",
                 "no-confidence-wt", "constant-lr", "alt-confidence"]:
        v = av[name]
        pw, pe, rg = v["p_wrong"], v["p_efficient"], v["regret"]
        cell = (f"{pretty[name]} & {pw['p']:.2f} {_ci(pw['lo'], pw['hi'])} "
                f"& {pe['p']:.2f} {_ci(pe['lo'], pe['hi'])} "
                f"& {rg['mean']:,.0f} [{rg['lo']:,.0f}, {rg['hi']:,.0f}]")
        if name == "full":
            cell += r" & --- \\"
        else:
            c = con[name]["d_p_wrong"]
            cell += f" & ${c['diff']:+.2f}$ [{c['lo']:+.2f}, {c['hi']:+.2f}] \\\\"
        L.append(cell)
    L += [r"\bottomrule\end{tabular}", r"\end{table}"]
    open(f"{TABDIR}/results_table.tex", "w").write("\n".join(L) + "\n")


def _gamma(p):
    return 1 - p.b_self if p.B is None else 1 - np.diag(np.asarray(p.B))[0]


def write_scenarios_table(scale):
    S = SCALE[scale]
    rt, rp = S["reps_traj"], S["reps_phase"]
    rows = [
        ("Fig.~2 efficient", scenarios.efficient(scale), rt, "101"),
        ("Fig.~2 wrong", scenarios.wrong(scale), rt, "102"),
        ("Fig.~2 polarised", scenarios.polarised(scale), rt, "103"),
        ("Fig.~3 phase ($\\lambda,\\Gamma$ swept)", scenarios.phase_base(scale), rp, "700+"),
        ("Fig.~4 ablation point", scenarios.ablation_point(scale), min(rt, 400), "CRN 20260617"),
        ("Fig.~5 confidence", scenarios.confidence_scenario(scale), 60, "303"),
        ("Fig.~6 four-community", scenarios.quotient_many(scale), min(rt, 250), "401"),
    ]
    L = ["% Auto-generated -- scenario parameters.",
         r"\begin{table}[t]\centering\footnotesize",
         r"\caption{Scenario parameters for all reported figures (standard scale). "
         r"$N$ is total agents, $T$ horizon, $R$ replications, $\Delta\mu=\mu_1-\mu_2$, "
         r"$\lambda$ anticipatory weight, $\eta$ retrospective weight, "
         r"$\Gamma=1-B_{cc}$ permeability. Regime threshold $0.9$ throughout. "
         r"Configuration: \texttt{code/credibility/scenarios.py}.}",
         r"\label{tab:scenarios}",
         r"\resizebox{\textwidth}{!}{\begin{tabular}{lcccccccl}\toprule",
         r"Scenario & $N$ & $T$ & $R$ & $\Delta\mu$ & $\lambda$ & $\eta$ & $\Gamma$ & init. lead \\ \midrule"]
    for label, p, reps, seed in rows:
        dmu = p.mu[0] - p.mu[1]
        q = p.q_init_array()
        lead = "neutral" if np.allclose(q, 0.5) else "asym."
        lam = "[0,1.6]" if "swept" in label else f"{p.lam:.2f}"
        gam = "[.01,.5]" if "swept" in label else f"{_gamma(p):.2f}"
        L.append(f"{label} & {p.N} & {p.T} & {reps} & {dmu:.2f} & {lam} & "
                 f"{p.eta:.2f} & {gam} & {lead} \\\\")
    L += [r"\bottomrule\end{tabular}}", r"\end{table}"]
    open(f"{TABDIR}/table_scenarios.tex", "w").write("\n".join(L) + "\n")


def write_default_params_table():
    p = Params()
    rows = [
        (r"$\beta$", p.beta, "value sensitivity (drift scaling)", "beta"),
        (r"$\sigma$", p.sigma, "internal decision noise", "sigma"),
        (r"$a$", p.a_thr, "speed--accuracy threshold", "a\\_thr"),
        (r"$\kappa_1$", p.kappa1, "confidence: evidence weight", "kappa1"),
        (r"$\kappa_2$", p.kappa2, "confidence: decision-time weight", "kappa2"),
        (r"$\tau_0$", p.tau0, "reaction-time scale", "tau0"),
        (r"$\alpha^{\min}$", p.alpha_min, "min reward learning rate", "alpha\\_min"),
        (r"$\alpha^{\max}$", p.alpha_max, "max reward learning rate", "alpha\\_max"),
        (r"$\gamma$", p.gamma, "retrospective credit-assignment scale", "gamma"),
        (r"$\omega$", p.omega, "social learning-rate exponent", "omega"),
        (r"$\varepsilon$", p.eps_soc, r"$\bar C$ denominator floor", "eps\\_soc"),
        ("RT disp.", p.rt_dispersion, "reaction-time squared CV", "rt\\_dispersion"),
    ]
    L = ["% Auto-generated -- default parameters.",
         r"\begin{table}[t]\centering\small",
         r"\caption{Global default parameters (\texttt{code/credibility/config.py}). "
         r"Confidence map is \texttt{decision} (Eq.~\ref{eq:confidence}); values are "
         r"projected to $[0,1]$ each trial; reaction times use the inverse-Gaussian "
         r"approximation.}",
         r"\label{tab:defaults}",
         r"\begin{tabular}{llcl}\toprule",
         r"Symbol & Default & Role & Config key \\ \midrule"]
    for sym, val, role, key in rows:
        L.append(f"{sym} & {val} & {role} & \\texttt{{{key}}} \\\\")
    L += [r"\bottomrule\end{tabular}", r"\end{table}"]
    open(f"{TABDIR}/table_default_params.tex", "w").write("\n".join(L) + "\n")


def write_code_map_table():
    rows = [
        ("Anticipatory signal", r"Eq.~\ref{eq:Si}", "model.py: anticipatory\\_field\\_block", "test\\_quotient\\_field\\_exact"),
        ("Augmented value", r"Eq.~\ref{eq:V}", "model.py: simulate\\_blocks", "test\\_block\\_dense\\_*"),
        ("DDM choice", r"Eq.~\ref{eq:choiceprob}", "ddm.py: choice\\_prob\\_up", "test\\_ddm\\_choice\\_*"),
        ("Reaction time", r"\S\ref{sec:model}", "ddm.py: sample\\_decision\\_time", "test\\_ddm\\_mean\\_fpt\\_*"),
        ("Confidence", r"Eq.~\ref{eq:confidence}", "confidence.py", "test\\_confidence\\_bounded"),
        ("Private learning", r"Eq.~\ref{eq:privatelr}", "model.py: \\_private\\_lr", "test\\_simultaneous\\_*"),
        ("Retrospective learning", r"Eq.~\ref{eq:socpe}", "model.py: value\\_update\\_*", "test\\_self\\_weighting\\_*"),
        ("Bounded values", r"Eq.~\ref{eq:update}", "model.py: np.clip", "test\\_values\\_bounded"),
        ("Regime classification", r"\S\ref{sec:design}", "metrics.py: classify\\_regime", "test\\_regime\\_classification"),
        ("Quotient (meso)", r"Eq.~\ref{eq:quotientfield}", "model.py: simulate\\_meso", "test\\_meso\\_*"),
        ("Uncertainty", r"\S\ref{sec:identification}", "uncertainty.py", "---"),
    ]
    L = ["% Auto-generated -- code map.",
         r"\begin{table}[t]\centering\small",
         r"\caption{Equation-to-code-to-test map. Code paths are under "
         r"\texttt{code/credibility/}; tests under \texttt{code/tests/test\_credibility.py}.}",
         r"\label{tab:codemap}",
         r"\begin{tabular}{llll}\toprule",
         r"Model element & Equation & Code & Test \\ \midrule"]
    for el, eq, code, test in rows:
        L.append(f"{el} & {eq} & \\texttt{{{code}}} & \\texttt{{{test}}} \\\\")
    L += [r"\bottomrule\end{tabular}", r"\end{table}"]
    open(f"{TABDIR}/table_code_map.tex", "w").write("\n".join(L) + "\n")


def write_robustness_table(scale):
    s = json.load(open(f"{common.RESULTS}/robustness_{scale}.json"))
    L = ["% Auto-generated -- robustness summary.",
         r"\begin{table}[t]\centering\small",
         r"\caption{Robustness summary (Appendix~\ref{app:robust}). Entries are the "
         r"dominant-regime area fractions of the $(\lambda,\Gamma)$ plane, or P(wrong) "
         r"at the operating point, as indicated. Full tables: "
         r"\texttt{paper/tables/robustness\_*.csv}.}",
         r"\label{tab:robustness}",
         r"\begin{tabular}{lll}\toprule",
         r"Check & Variation & Result \\ \midrule"]
    r1 = s["R1"]
    L.append(r"R1 threshold & $0.80/0.90/0.95$ & wrong-area "
             f"$={r1['0.8']['wrong']:.2f}/{r1['0.9']['wrong']:.2f}/{r1['0.95']['wrong']:.2f}$ (invariant) \\\\")
    L.append(r"R2 horizon & $T=200\!-\!1000$ & near-zero stays unresolved; "
             r"corrective/distortive stable \\")
    r3 = s["R3"]
    L.append(r"R3 initial lead & $\delta=0\!-\!0.16$ & "
             f"P(wrong) $={r3['lead_0.0']['wrong']:.2f}\\!\\to\\!{r3['lead_0.04']['wrong']:.2f}$ "
             r"(small lead suffices) \\")
    r4 = s["R4"]
    L.append(r"R4 reward gap & $|\Delta\mu|=0.02\!-\!0.20$ & "
             f"P(wrong) $={r4['gap_0.02']['wrong']:.2f}\\!-\\!{r4['gap_0.2']['wrong']:.2f}$ "
             r"(persists) \\")
    r5 = s["R5"]
    L.append(r"R5 random graphs & balanced/SBM/noisy & "
             f"distortive P(wrong) $={r5['distortive_balanced']['wrong']:.2f}/"
             f"{r5['distortive_weighted_sbm']['wrong']:.2f}/{r5['distortive_noisy_W']['wrong']:.2f}$ \\\\")
    r6 = s["R6"]
    L.append(r"R6 grid resolution & $7^2/9^2/13^2$ & wrong-area "
             f"$={r6['7x7']['wrong']:.2f}/{r6['9x9']['wrong']:.2f}/{r6['13x13']['wrong']:.2f}$ \\\\")
    r7 = s["R7"]
    L.append(r"R7 RT approximation & inverse-Gaussian vs.\ mean & wrong-area "
             f"$={r7['ig']['wrong']:.2f}$ vs.\\ ${r7['mean']['wrong']:.2f}$ \\\\")
    L += [r"\bottomrule\end{tabular}", r"\end{table}"]
    open(f"{TABDIR}/table_robustness.tex", "w").write("\n".join(L) + "\n")


def main():
    scale = common.get_scale()
    write_results_table(scale)
    write_scenarios_table(scale)
    write_default_params_table()
    write_code_map_table()
    write_robustness_table(scale)
    print(f"wrote 5 LaTeX tables to {TABDIR}")


if __name__ == "__main__":
    main()
